# Generated by Django 4.2.8 on 2023-12-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0006_alter_episode_rating_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=10000, null=True, verbose_name='Poster'),
        ),
    ]
